// <auto-generated />
using System;
using Electronic_Health_Record.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electronic_Health_Record.Server.Data.Migrations
{
    [DbContext(typeof(ElectronicHealthRecordDbContext))]
    [Migration("20260901053000_RemovePasswordAlgo")]
    partial class RemovePasswordAlgo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Admin");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AdminID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admin", null, t =>
                        {
                            t.HasCheckConstraint("CK_Admin_Role", "[Role] IN ('SuperAdmin','Admin')");
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.FamilyMedicalHistory", b =>
                {
                    b.Property<int>("FMHID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FMHID"));

                    b.Property<int?>("ConditionID")
                        .HasColumnType("int");

                    b.Property<string>("ConditionOther")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsNone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("FMHID");

                    b.HasIndex("ConditionID");

                    b.HasIndex("FormID");

                    b.ToTable("FamilyMedicalHistory", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.MedicalCondition", b =>
                {
                    b.Property<int>("ConditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionID"));

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConditionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConditionID");

                    b.HasIndex("ConditionName")
                        .IsUnique();

                    b.ToTable("MedicalCondition", (string)null);

                    b.HasData(
                        new
                        {
                            ConditionID = 1,
                            ConditionName = "Hypertension"
                        },
                        new
                        {
                            ConditionID = 2,
                            ConditionName = "Stroke"
                        },
                        new
                        {
                            ConditionID = 3,
                            ConditionName = "Diabetes Mellitus"
                        },
                        new
                        {
                            ConditionID = 4,
                            ConditionName = "Tuberculosis"
                        },
                        new
                        {
                            ConditionID = 5,
                            ConditionName = "Bronchial Asthma"
                        },
                        new
                        {
                            ConditionID = 6,
                            ConditionName = "Cancer"
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PastMedicalHistory", b =>
                {
                    b.Property<int>("PMHID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PMHID"));

                    b.Property<int?>("ConditionID")
                        .HasColumnType("int");

                    b.Property<string>("ConditionOther")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Dosage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaintenanceDrugGeneric")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<short?>("YearDiagnosed")
                        .HasColumnType("smallint");

                    b.HasKey("PMHID");

                    b.HasIndex("ConditionID");

                    b.HasIndex("FormID");

                    b.ToTable("PastMedicalHistory", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AgencyOffice")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("PatientID");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.Physician", b =>
                {
                    b.Property<int>("PhysicianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PRCLicenseNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PhysicianID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Physician_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PRCLicenseNo")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_Physician_Username")
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Physician", null, t =>
                        {
                            t.HasCheckConstraint("CK_Physician_CredentialSet", "([Username] IS NULL AND [Email] IS NULL AND [PasswordHash] IS NULL) OR ([Username] IS NOT NULL AND [Email] IS NOT NULL AND [PasswordHash] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.SocialHistory", b =>
                {
                    b.Property<int>("SocialHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialHistoryID"));

                    b.Property<string>("AlcoholType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("DrinkFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DrinksPerSession")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DrunkFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExerciseFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExerciseType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<bool?>("HasBeenDrunk")
                        .HasColumnType("bit");

                    b.Property<short?>("SmokingSticksPerDay")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("SocialHistoryID");

                    b.HasIndex("FormID")
                        .IsUnique();

                    b.ToTable("SocialHistory", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.UserSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhysicianID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.HasKey("SessionID");

                    b.HasIndex("AdminID");

                    b.HasIndex("PhysicianID");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("UserSession", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSession_ExactlyOnePrincipal", "([AdminID] IS NOT NULL AND [PhysicianID] IS NULL) OR ([AdminID] IS NULL AND [PhysicianID] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.WellnessForm", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormID"));

                    b.Property<int?>("AssignedPhysicianID")
                        .HasColumnType("int");

                    b.Property<decimal?>("BMI")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<short?>("BPDiastolic")
                        .HasColumnType("smallint");

                    b.Property<short?>("BPSystolic")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int?>("CreatedByAdminID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FormDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CAST(SYSDATETIME() AS date)");

                    b.Property<short?>("HeartRate")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("IdealBMI")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImpressionClinical")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ManagementTreatment")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("RecommendedDiagnosticTest")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<short?>("RespRate")
                        .HasColumnType("smallint");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SignedByPhysicianID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal?>("TempCelsius")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int?>("UpdatedByAdminID")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("FormID");

                    b.HasIndex("AssignedPhysicianID");

                    b.HasIndex("CreatedByAdminID");

                    b.HasIndex("PatientID");

                    b.HasIndex("SignedByPhysicianID");

                    b.HasIndex("UpdatedByAdminID");

                    b.HasIndex("Status", "AssignedPhysicianID")
                        .HasDatabaseName("IX_WellnessForm_Status_AssignedPhysicianID");

                    b.ToTable("WellnessForm", null, t =>
                        {
                            t.HasCheckConstraint("CK_WellnessForm_AssignedWhenPending", "[Status] = 'Draft' OR [AssignedPhysicianID] IS NOT NULL");

                            t.HasCheckConstraint("CK_WellnessForm_SignedIntegrity", "[Status] <> 'Signed' OR ([AssignedPhysicianID] IS NOT NULL AND [SignedByPhysicianID] IS NOT NULL AND [Signature] IS NOT NULL AND [SignedAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_WellnessForm_Status", "[Status] IN ('Draft','PendingSignature','Signed')");
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.FamilyMedicalHistory", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.MedicalCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.WellnessForm", null)
                        .WithMany()
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PastMedicalHistory", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.MedicalCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.WellnessForm", null)
                        .WithMany()
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.SocialHistory", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.WellnessForm", null)
                        .WithOne()
                        .HasForeignKey("Electronic_Health_Record.Server.Models.SocialHistory", "FormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.UserSession", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.Physician", null)
                        .WithMany()
                        .HasForeignKey("PhysicianID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.WellnessForm", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.Physician", null)
                        .WithMany()
                        .HasForeignKey("AssignedPhysicianID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAdminID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Electronic_Health_Record.Server.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Electronic_Health_Record.Server.Models.Physician", null)
                        .WithMany()
                        .HasForeignKey("SignedByPhysicianID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
