using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Electronic_Health_Record.Server.Data.Migrations
{
    /// <summary>
    /// Repoints every timestamp column default from SYSDATETIME() (the database
    /// server's local clock) to SYSUTCDATETIME().
    ///
    /// Every timestamp written from C# uses DateTime.UtcNow, but these column
    /// defaults used the server's local time. Both landed in the same offset-less
    /// datetime2 column, so a row's meaning depended on which path inserted it --
    /// and rows inserted by the default read 8 hours ahead of the rest once
    /// rendered as UTC.
    ///
    /// WellnessForm.FormDate is the exception: it is a calendar date, so it is
    /// derived from Philippine wall-clock time. A UTC-derived date would file
    /// anything submitted before 8 AM PHT under the previous day.
    ///
    /// Written by hand rather than scaffolded: the constraint names are
    /// auto-generated by SQL Server, so they have to be looked up in
    /// sys.default_constraints instead of being named literally.
    /// </summary>
    public partial class UseUtcTimestampDefaults : Migration
    {
        // (table, column, isCalendarDate)
        private static readonly (string Table, string Column, bool IsDate)[] Columns = new[]
        {
            ("Patient", "LastSyncedAt", false),
            ("Patient", "CreatedAt", false),
            ("Patient", "UpdatedAt", false),
            ("Physician", "CreatedAt", false),
            ("Physician", "UpdatedAt", false),
            ("Admin", "CreatedAt", false),
            ("Admin", "UpdatedAt", false),
            ("AdminSession", "CreatedAt", false),
            ("PhysicianSession", "CreatedAt", false),
            ("PatientAccount", "ProvisionedAt", false),
            ("PatientAccount", "CreatedAt", false),
            ("PatientAccount", "UpdatedAt", false),
            ("PatientSession", "CreatedAt", false),
            ("WellnessForm", "FormDate", true),
            ("WellnessForm", "CreatedAt", false),
            ("WellnessForm", "UpdatedAt", false),
            ("ChargeItem", "CreatedAt", false),
            ("ChargeItem", "UpdatedAt", false),
            ("WellnessFormCharge", "CreatedAt", false),
            ("BillingForm", "CreatedAt", false),
            ("SocialHistory", "CreatedAt", false),
            ("SocialHistory", "UpdatedAt", false),
            ("Exercise", "CreatedAt", false),
            ("Exercise", "UpdatedAt", false),
            ("DentalAssessment", "CreatedAt", false),
            ("DentalAssessment", "UpdatedAt", false),
            ("VisionAssessment", "CreatedAt", false),
            ("VisionAssessment", "UpdatedAt", false),
            ("FamilyMedicalHistory", "CreatedAt", false),
            ("FamilyMedicalHistory", "UpdatedAt", false),
            ("PastMedicalHistory", "CreatedAt", false),
            ("PastMedicalHistory", "UpdatedAt", false),
            ("AssessmentQuestion", "CreatedAt", false),
            ("AssessmentAnswer", "CreatedAt", false),
            ("WellnessFormAuditLog", "OccurredAt", false),
        };

        private const string PhilippineDate =
            "CAST(SYSUTCDATETIME() AT TIME ZONE 'UTC' AT TIME ZONE 'Singapore Standard Time' AS date)";

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            foreach (var (table, column, isDate) in Columns)
            {
                var expression = isDate ? PhilippineDate : "SYSUTCDATETIME()";
                Repoint(migrationBuilder, table, column, expression);
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            foreach (var (table, column, isDate) in Columns)
            {
                var expression = isDate ? "CAST(SYSDATETIME() AS date)" : "SYSDATETIME()";
                Repoint(migrationBuilder, table, column, expression);
            }
        }

        // Only the default constraint is touched: existing row values are left
        // exactly as they are, so this migration cannot lose or alter data.
        private static void Repoint(
            MigrationBuilder migrationBuilder,
            string table,
            string column,
            string expression)
        {
            migrationBuilder.Sql($@"
DECLARE @constraint sysname;

SELECT @constraint = dc.name
FROM sys.default_constraints AS dc
JOIN sys.columns AS c
    ON c.object_id = dc.parent_object_id
   AND c.column_id = dc.parent_column_id
WHERE dc.parent_object_id = OBJECT_ID(N'[{table}]')
  AND c.name = N'{column}';

IF @constraint IS NOT NULL
    EXEC(N'ALTER TABLE [{table}] DROP CONSTRAINT [' + @constraint + N']');

IF OBJECT_ID(N'[{table}]') IS NOT NULL
    ALTER TABLE [{table}] ADD DEFAULT {expression} FOR [{column}];
");
        }
    }
}
