// <auto-generated />
using System;
using Electronic_Health_Record.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electronic_Health_Record.Server.Data.Migrations
{
    [DbContext(typeof(ElectronicHealthRecordDbContext))]
    [Migration("20260903090000_AddAdminRole")]
    partial class AddAdminRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("ContactNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("admin");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AdminID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admin", null, t =>
                        {
                            t.HasCheckConstraint("CK_Admin_Role", "Role IN ('admin', 'superadmin')");
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AdminSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.HasKey("SessionID");

                    b.HasIndex("AdminID");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AdminSession", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AssessmentAnswer", b =>
                {
                    b.Property<int>("AnswerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<int>("OptionID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.HasKey("AnswerID");

                    b.HasIndex("OptionID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("FormID", "QuestionID")
                        .IsUnique();

                    b.ToTable("AssessmentAnswer", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AssessmentCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssessmentCategory", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            DisplayOrder = (byte)1,
                            Name = "Mental Health"
                        },
                        new
                        {
                            CategoryID = 2,
                            DisplayOrder = (byte)2,
                            Name = "Physical Health"
                        },
                        new
                        {
                            CategoryID = 3,
                            DisplayOrder = (byte)3,
                            Name = "Spiritual Health"
                        },
                        new
                        {
                            CategoryID = 4,
                            DisplayOrder = (byte)4,
                            Name = "Social Health"
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AssessmentOption", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionID"));

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.HasKey("OptionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("AssessmentOption", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssessmentOption_Score", "Score BETWEEN 1 AND 4");
                        });

                    b.HasData(
                        new
                        {
                            OptionID = 1,
                            DisplayOrder = (byte)1,
                            OptionText = "None",
                            QuestionID = 1,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 2,
                            DisplayOrder = (byte)2,
                            OptionText = "Mild",
                            QuestionID = 1,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 3,
                            DisplayOrder = (byte)3,
                            OptionText = "Moderate",
                            QuestionID = 1,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 4,
                            DisplayOrder = (byte)4,
                            OptionText = "Severe",
                            QuestionID = 1,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 5,
                            DisplayOrder = (byte)1,
                            OptionText = "Less than 5 hrs",
                            QuestionID = 2,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 6,
                            DisplayOrder = (byte)2,
                            OptionText = "5-6 hrs",
                            QuestionID = 2,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 7,
                            DisplayOrder = (byte)3,
                            OptionText = "7-8 hrs",
                            QuestionID = 2,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 8,
                            DisplayOrder = (byte)4,
                            OptionText = "More than 8 hrs",
                            QuestionID = 2,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 9,
                            DisplayOrder = (byte)1,
                            OptionText = "Very Good",
                            QuestionID = 3,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 10,
                            DisplayOrder = (byte)2,
                            OptionText = "Good",
                            QuestionID = 3,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 11,
                            DisplayOrder = (byte)3,
                            OptionText = "Fair",
                            QuestionID = 3,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 12,
                            DisplayOrder = (byte)4,
                            OptionText = "Poor",
                            QuestionID = 3,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 13,
                            DisplayOrder = (byte)1,
                            OptionText = "Never",
                            QuestionID = 4,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 14,
                            DisplayOrder = (byte)2,
                            OptionText = "Rarely",
                            QuestionID = 4,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 15,
                            DisplayOrder = (byte)3,
                            OptionText = "Sometimes",
                            QuestionID = 4,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 16,
                            DisplayOrder = (byte)4,
                            OptionText = "Often",
                            QuestionID = 4,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 17,
                            DisplayOrder = (byte)1,
                            OptionText = "Never",
                            QuestionID = 5,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 18,
                            DisplayOrder = (byte)2,
                            OptionText = "Rarely",
                            QuestionID = 5,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 19,
                            DisplayOrder = (byte)3,
                            OptionText = "Sometimes",
                            QuestionID = 5,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 20,
                            DisplayOrder = (byte)4,
                            OptionText = "Often",
                            QuestionID = 5,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 21,
                            DisplayOrder = (byte)1,
                            OptionText = "None",
                            QuestionID = 6,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 22,
                            DisplayOrder = (byte)2,
                            OptionText = "Mild",
                            QuestionID = 6,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 23,
                            DisplayOrder = (byte)3,
                            OptionText = "Moderate",
                            QuestionID = 6,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 24,
                            DisplayOrder = (byte)4,
                            OptionText = "Severe",
                            QuestionID = 6,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 25,
                            DisplayOrder = (byte)1,
                            OptionText = "Never",
                            QuestionID = 7,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 26,
                            DisplayOrder = (byte)2,
                            OptionText = "Rarely",
                            QuestionID = 7,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 27,
                            DisplayOrder = (byte)3,
                            OptionText = "Sometimes",
                            QuestionID = 7,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 28,
                            DisplayOrder = (byte)4,
                            OptionText = "Always",
                            QuestionID = 7,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 29,
                            DisplayOrder = (byte)1,
                            OptionText = "Very Good",
                            QuestionID = 8,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 30,
                            DisplayOrder = (byte)2,
                            OptionText = "Good",
                            QuestionID = 8,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 31,
                            DisplayOrder = (byte)3,
                            OptionText = "Fair",
                            QuestionID = 8,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 32,
                            DisplayOrder = (byte)4,
                            OptionText = "Poor",
                            QuestionID = 8,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 33,
                            DisplayOrder = (byte)1,
                            OptionText = "Very Regular",
                            QuestionID = 9,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 34,
                            DisplayOrder = (byte)2,
                            OptionText = "Regular",
                            QuestionID = 9,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 35,
                            DisplayOrder = (byte)3,
                            OptionText = "Irregular",
                            QuestionID = 9,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 36,
                            DisplayOrder = (byte)4,
                            OptionText = "Very Irregular",
                            QuestionID = 9,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 37,
                            DisplayOrder = (byte)1,
                            OptionText = "None",
                            QuestionID = 10,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 38,
                            DisplayOrder = (byte)2,
                            OptionText = "Mild",
                            QuestionID = 10,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 39,
                            DisplayOrder = (byte)3,
                            OptionText = "Moderate",
                            QuestionID = 10,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 40,
                            DisplayOrder = (byte)4,
                            OptionText = "Severe",
                            QuestionID = 10,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 41,
                            DisplayOrder = (byte)1,
                            OptionText = "Strongly Agree",
                            QuestionID = 11,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 42,
                            DisplayOrder = (byte)2,
                            OptionText = "Agree",
                            QuestionID = 11,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 43,
                            DisplayOrder = (byte)3,
                            OptionText = "Disagree",
                            QuestionID = 11,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 44,
                            DisplayOrder = (byte)4,
                            OptionText = "Strongly Disagree",
                            QuestionID = 11,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 45,
                            DisplayOrder = (byte)1,
                            OptionText = "Always",
                            QuestionID = 12,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 46,
                            DisplayOrder = (byte)2,
                            OptionText = "Often",
                            QuestionID = 12,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 47,
                            DisplayOrder = (byte)3,
                            OptionText = "Rarely",
                            QuestionID = 12,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 48,
                            DisplayOrder = (byte)4,
                            OptionText = "Never",
                            QuestionID = 12,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 49,
                            DisplayOrder = (byte)1,
                            OptionText = "Always",
                            QuestionID = 13,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 50,
                            DisplayOrder = (byte)2,
                            OptionText = "Often",
                            QuestionID = 13,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 51,
                            DisplayOrder = (byte)3,
                            OptionText = "Rarely",
                            QuestionID = 13,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 52,
                            DisplayOrder = (byte)4,
                            OptionText = "Never",
                            QuestionID = 13,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 53,
                            DisplayOrder = (byte)1,
                            OptionText = "Excellent",
                            QuestionID = 14,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 54,
                            DisplayOrder = (byte)2,
                            OptionText = "Good",
                            QuestionID = 14,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 55,
                            DisplayOrder = (byte)3,
                            OptionText = "Fair",
                            QuestionID = 14,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 56,
                            DisplayOrder = (byte)4,
                            OptionText = "Poor",
                            QuestionID = 14,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 57,
                            DisplayOrder = (byte)1,
                            OptionText = "Very Satisfied",
                            QuestionID = 15,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 58,
                            DisplayOrder = (byte)2,
                            OptionText = "Satisfied",
                            QuestionID = 15,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 59,
                            DisplayOrder = (byte)3,
                            OptionText = "Unsatisfied",
                            QuestionID = 15,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 60,
                            DisplayOrder = (byte)4,
                            OptionText = "Very Unsatisfied",
                            QuestionID = 15,
                            Score = (byte)1
                        },
                        new
                        {
                            OptionID = 61,
                            DisplayOrder = (byte)1,
                            OptionText = "Always",
                            QuestionID = 16,
                            Score = (byte)4
                        },
                        new
                        {
                            OptionID = 62,
                            DisplayOrder = (byte)2,
                            OptionText = "Most of the time",
                            QuestionID = 16,
                            Score = (byte)3
                        },
                        new
                        {
                            OptionID = 63,
                            DisplayOrder = (byte)3,
                            OptionText = "Rarely",
                            QuestionID = 16,
                            Score = (byte)2
                        },
                        new
                        {
                            OptionID = 64,
                            DisplayOrder = (byte)4,
                            OptionText = "Never",
                            QuestionID = 16,
                            Score = (byte)1
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AssessmentQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("QuestionID");

                    b.HasIndex("CategoryID");

                    b.ToTable("AssessmentQuestion", (string)null);

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)1,
                            IsActive = true,
                            QuestionText = "How would you rate your current stress level?"
                        },
                        new
                        {
                            QuestionID = 2,
                            CategoryID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)2,
                            IsActive = true,
                            QuestionText = "How many hours of sleep do you get on average?"
                        },
                        new
                        {
                            QuestionID = 3,
                            CategoryID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)3,
                            IsActive = true,
                            QuestionText = "How would you describe your general mood lately?"
                        },
                        new
                        {
                            QuestionID = 4,
                            CategoryID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)4,
                            IsActive = true,
                            QuestionText = "Do you experience frequent anxiety or worry?"
                        },
                        new
                        {
                            QuestionID = 5,
                            CategoryID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)5,
                            IsActive = true,
                            QuestionText = "Do you have difficulty concentrating or focusing?"
                        },
                        new
                        {
                            QuestionID = 6,
                            CategoryID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)1,
                            IsActive = true,
                            QuestionText = "Do you experience any chronic pain?"
                        },
                        new
                        {
                            QuestionID = 7,
                            CategoryID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)2,
                            IsActive = true,
                            QuestionText = "How often do you feel fatigued during the day?"
                        },
                        new
                        {
                            QuestionID = 8,
                            CategoryID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)3,
                            IsActive = true,
                            QuestionText = "How is your appetite?"
                        },
                        new
                        {
                            QuestionID = 9,
                            CategoryID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)4,
                            IsActive = true,
                            QuestionText = "How regular are your bowel movements?"
                        },
                        new
                        {
                            QuestionID = 10,
                            CategoryID = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)5,
                            IsActive = true,
                            QuestionText = "Do you experience any urinary problems?"
                        },
                        new
                        {
                            QuestionID = 11,
                            CategoryID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)1,
                            IsActive = true,
                            QuestionText = "Do you have a clear sense of purpose in life?"
                        },
                        new
                        {
                            QuestionID = 12,
                            CategoryID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)2,
                            IsActive = true,
                            QuestionText = "Do you feel inner peace most of the time?"
                        },
                        new
                        {
                            QuestionID = 13,
                            CategoryID = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)3,
                            IsActive = true,
                            QuestionText = "Do you regularly practice gratitude?"
                        },
                        new
                        {
                            QuestionID = 14,
                            CategoryID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)1,
                            IsActive = true,
                            QuestionText = "How would you rate your relationships with family and friends?"
                        },
                        new
                        {
                            QuestionID = 15,
                            CategoryID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)2,
                            IsActive = true,
                            QuestionText = "How satisfied are you with your work-life balance?"
                        },
                        new
                        {
                            QuestionID = 16,
                            CategoryID = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = (byte)3,
                            IsActive = true,
                            QuestionText = "Do you have people you can rely on for support?"
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.FamilyMedicalHistory", b =>
                {
                    b.Property<int>("FMHID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FMHID"));

                    b.Property<int?>("ConditionID")
                        .HasColumnType("int");

                    b.Property<string>("ConditionOther")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("FamilyMembers")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<bool?>("IsNone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("FMHID");

                    b.HasIndex("ConditionID");

                    b.HasIndex("FormID");

                    b.ToTable("FamilyMedicalHistory", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.MedicalCondition", b =>
                {
                    b.Property<int>("ConditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionID"));

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConditionType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConditionID");

                    b.HasIndex("ConditionName")
                        .IsUnique();

                    b.ToTable("MedicalCondition", (string)null);

                    b.HasData(
                        new
                        {
                            ConditionID = 1,
                            ConditionName = "Hypertension"
                        },
                        new
                        {
                            ConditionID = 2,
                            ConditionName = "Stroke"
                        },
                        new
                        {
                            ConditionID = 3,
                            ConditionName = "Diabetes Mellitus"
                        },
                        new
                        {
                            ConditionID = 4,
                            ConditionName = "Tuberculosis"
                        },
                        new
                        {
                            ConditionID = 5,
                            ConditionName = "Bronchial Asthma"
                        },
                        new
                        {
                            ConditionID = 6,
                            ConditionName = "Cancer"
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PastMedicalHistory", b =>
                {
                    b.Property<int>("PMHID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PMHID"));

                    b.Property<int?>("ConditionID")
                        .HasColumnType("int");

                    b.Property<string>("ConditionOther")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Dosage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaintenanceDrugGeneric")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<short?>("YearDiagnosed")
                        .HasColumnType("smallint");

                    b.HasKey("PMHID");

                    b.HasIndex("ConditionID");

                    b.HasIndex("FormID");

                    b.ToTable("PastMedicalHistory", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AgencyOffice")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("ExternalEmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("PatientID");

                    b.HasIndex("ExternalEmployeeId")
                        .IsUnique();

                    b.HasIndex("Surname", "FirstName");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PatientAccount", b =>
                {
                    b.Property<int>("PatientAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientAccountID"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProvisionedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Provisioned");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PatientAccountID");

                    b.HasIndex("PatientID")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("PatientAccount", null, t =>
                        {
                            t.HasCheckConstraint("CK_PatientAccount_Activation", "Status <> 'Active' OR (PasswordHash IS NOT NULL AND ActivatedAt IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PatientSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientAccountID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.HasKey("SessionID");

                    b.HasIndex("PatientAccountID");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PatientSession", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.Physician", b =>
                {
                    b.Property<int>("PhysicianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhysicianID"));

                    b.Property<string>("ContactNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PRCLicenseNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PhysicianID");

                    b.HasIndex("PRCLicenseNo")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Physician", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PhysicianSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhysicianID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.HasKey("SessionID");

                    b.HasIndex("PhysicianID");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PhysicianSession", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.SocialHistory", b =>
                {
                    b.Property<int>("SocialHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialHistoryID"));

                    b.Property<string>("AlcoholType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("DrinkFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DrinksPerSession")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DrunkFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExerciseFrequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExerciseType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<bool?>("HasBeenDrunk")
                        .HasColumnType("bit");

                    b.Property<short?>("SmokingSticksPerDay")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("SocialHistoryID");

                    b.HasIndex("FormID")
                        .IsUnique();

                    b.ToTable("SocialHistory", (string)null);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.WellnessForm", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormID"));

                    b.Property<decimal?>("BMI")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<short?>("BPDiastolic")
                        .HasColumnType("smallint");

                    b.Property<short?>("BPSystolic")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int?>("CreatedByAdminID")
                        .HasColumnType("int");

                    b.Property<byte>("CurrentStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FormDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CAST(SYSDATETIME() AS date)");

                    b.Property<short?>("HeartRate")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("IdealBMI")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImpressionClinical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagementTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("PhysicianID")
                        .HasColumnType("int");

                    b.Property<string>("RecommendedDiagnosticTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("RespRate")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Station1AdminID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Station1SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Station2AdminID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Station2SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Station3SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("PendingAssessment");

                    b.Property<decimal?>("TempCelsius")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int?>("UpdatedByAdminID")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("FormID");

                    b.HasIndex("CreatedByAdminID");

                    b.HasIndex("PhysicianID");

                    b.HasIndex("Station1AdminID");

                    b.HasIndex("Station2AdminID");

                    b.HasIndex("UpdatedByAdminID");

                    b.HasIndex("PatientID", "FormDate")
                        .HasDatabaseName("IX_WellnessForm_PatientID_FormDate");

                    b.HasIndex("Status", "FormDate")
                        .HasDatabaseName("IX_WellnessForm_Status_FormDate");

                    b.ToTable("WellnessForm", null, t =>
                        {
                            t.HasCheckConstraint("CK_WellnessForm_CompletedIsSigned", "Status <> 'Completed' OR (PhysicianID IS NOT NULL AND Signature IS NOT NULL AND SignedAt IS NOT NULL)");

                            t.HasCheckConstraint("CK_WellnessForm_CurrentStation", "CurrentStation IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_WellnessForm_Status", "Status IN ('PendingAssessment', 'PendingConsultation', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.WellnessFormAuditLog", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ActorID")
                        .HasColumnType("int");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FormID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("LogID");

                    b.HasIndex("FormID");

                    b.ToTable("WellnessFormAuditLog", null, t =>
                        {
                            t.HasCheckConstraint("CK_WellnessFormAuditLog_ActorType", "ActorType IN ('Admin', 'Physician', 'Patient', 'System')");
                        });
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AdminSession", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AssessmentAnswer", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.WellnessForm", null)
                        .WithMany()
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Electronic_Health_Record.Server.Models.AssessmentOption", null)
                        .WithMany()
                        .HasForeignKey("OptionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Electronic_Health_Record.Server.Models.AssessmentQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AssessmentOption", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.AssessmentQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.AssessmentQuestion", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.AssessmentCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.FamilyMedicalHistory", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.MedicalCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.WellnessForm", null)
                        .WithMany()
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PastMedicalHistory", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.MedicalCondition", null)
                        .WithMany()
                        .HasForeignKey("ConditionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.WellnessForm", null)
                        .WithMany()
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PatientAccount", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.Patient", null)
                        .WithOne()
                        .HasForeignKey("Electronic_Health_Record.Server.Models.PatientAccount", "PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PatientSession", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.PatientAccount", null)
                        .WithMany()
                        .HasForeignKey("PatientAccountID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.PhysicianSession", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.Physician", null)
                        .WithMany()
                        .HasForeignKey("PhysicianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.SocialHistory", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.WellnessForm", null)
                        .WithOne()
                        .HasForeignKey("Electronic_Health_Record.Server.Models.SocialHistory", "FormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.WellnessForm", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAdminID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Electronic_Health_Record.Server.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Electronic_Health_Record.Server.Models.Physician", null)
                        .WithMany()
                        .HasForeignKey("PhysicianID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("Station1AdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("Station2AdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Electronic_Health_Record.Server.Models.Admin", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Electronic_Health_Record.Server.Models.WellnessFormAuditLog", b =>
                {
                    b.HasOne("Electronic_Health_Record.Server.Models.WellnessForm", null)
                        .WithMany()
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
