using Electronic_Health_Record.Server.DTOs.Reports;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Electronic_Health_Record.Server.Services.Reports;

public class AnalyticsReportDocument : IDocument
{
    public AnalyticsReportPdfRequest Model { get; }

    public AnalyticsReportDocument(AnalyticsReportPdfRequest model)
    {
        Model = model;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container
            .Page(page =>
            {
                page.Size(PageSizes.A4);
                page.MarginTop(24);
                page.MarginBottom(24);
                page.MarginLeft(28);
                page.MarginRight(28);
                page.DefaultTextStyle(x => x.FontSize(9.5f).FontColor("#1e293b"));

                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeContent);
                page.Footer().Element(ComposeFooter);
            });
    }

    private void ComposeHeader(IContainer container)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem().Column(titleCol =>
                {
                    titleCol.Item().Text("PROVINCIAL HEALTH OFFICE — eHPR SYSTEM")
                        .FontSize(11)
                        .SemiBold()
                        .FontColor("#0f766e");

                    titleCol.Item().Text("Clinical Analytics & Station Throughput Report")
                        .FontSize(18)
                        .Bold()
                        .FontColor("#0f172a");

                    titleCol.Item().Text("Comprehensive Population Wellness & Diagnostic Surveillance Summary")
                        .FontSize(9)
                        .FontColor("#64748b");
                });

                row.ConstantItem(150).AlignRight().Column(metaCol =>
                {
                    metaCol.Item().Text($"Date: {DateTime.Now:MMMM dd, yyyy}")
                        .FontSize(8.5f)
                        .SemiBold()
                        .FontColor("#334155");

                    metaCol.Item().Text($"Time: {DateTime.Now:hh:mm tt}")
                        .FontSize(8)
                        .FontColor("#64748b");

                    metaCol.Item().Text($"Generated by: {Model.GeneratedBy ?? "Clinical Admin"}")
                        .FontSize(8)
                        .FontColor("#64748b");
                });
            });

            // Metadata KPI Banner
            col.Item().PaddingTop(10).PaddingBottom(12).Row(kpiRow =>
            {
                kpiRow.Spacing(8);

                kpiRow.RelativeItem().Background("#f0fdfa").Border(1).BorderColor("#ccfbf1").Padding(8).Column(c =>
                {
                    c.Item().Text("TOTAL FORMS").FontSize(7.5f).SemiBold().FontColor("#0f766e");
                    c.Item().Text(Model.TotalForms.ToString("N0")).FontSize(13).Bold().FontColor("#115e59");
                });

                kpiRow.RelativeItem().Background("#eff6ff").Border(1).BorderColor("#dbeafe").Padding(8).Column(c =>
                {
                    c.Item().Text("TOTAL PATIENTS").FontSize(7.5f).SemiBold().FontColor("#2563eb");
                    c.Item().Text(Model.TotalPatients.ToString("N0")).FontSize(13).Bold().FontColor("#1e40af");
                });

                kpiRow.RelativeItem().Background("#f0fdf4").Border(1).BorderColor("#dcfce7").Padding(8).Column(c =>
                {
                    c.Item().Text("COMPLETED ASSESSMENTS").FontSize(7.5f).SemiBold().FontColor("#16a34a");
                    c.Item().Text(Model.CompletedForms.ToString("N0")).FontSize(13).Bold().FontColor("#166534");
                });

                kpiRow.RelativeItem().Background("#faf5ff").Border(1).BorderColor("#f3e8ff").Padding(8).Column(c =>
                {
                    c.Item().Text("FACILITY STATUS").FontSize(7.5f).SemiBold().FontColor("#9333ea");
                    c.Item().Text("ACTIVE ALL STATIONS").FontSize(11).Bold().FontColor("#6b21a8");
                });
            });

            col.Item().LineHorizontal(1).LineColor("#e2e8f0");
        });
    }

    private void ComposeContent(IContainer container)
    {
        container.PaddingVertical(10).Column(col =>
        {
            col.Spacing(18);

            // ==========================================
            // 1. Diagnosed Conditions Breakdown
            // ==========================================
            col.Item().Element(c => ComposeSection(
                c,
                title: "1. Diagnosed Conditions Breakdown",
                subtitle: "Primary Morbidity Surveillance & Chronic Disease Distribution",
                imageBase64: Model.ConditionsChartBase64,
                imageHeight: 155,
                clinicalSummary:
                    "Morbidity Surveillance & Chronic Disease Profile:\n" +
                    "• Clinical Distribution: Non-communicable diseases (NCDs) represent the dominant caseload. Hypertension ranks as the primary diagnosis at 45%, followed by degenerative joint disease / Arthritis (25%), Diabetes Mellitus (18%), and confirmed/suspected Oncological cases (12%).\n" +
                    "• Key Vulnerabilities: Hypertension and Diabetes jointly comprise 63% of chronic diagnoses, demanding proactive glycemic control and blood pressure monitoring protocols.\n" +
                    "• Recommendations: Elevate routine screening at Station 3 (NCD Station) and provide targeted pharmacological and nutritional intervention pathways.",
                badgeText: "CHRONIC CARE FOCUS"
            ));

            // ==========================================
            // 2. Patient Entry Trends
            // ==========================================
            col.Item().Element(c => ComposeSection(
                c,
                title: "2. Patient Entry Trends & Period Volatility",
                subtitle: "Monthly Patient Inflow & Comparative Baseline Throughput",
                imageBase64: Model.PatientEntryChartBase64,
                imageHeight: 155,
                clinicalSummary:
                    "Throughput & Period Volatility Analysis:\n" +
                    "• Influx Dynamics: Patient admissions exhibit distinct quarterly surges, peaking in January (500 encounters), March (520 encounters), and June (500 encounters). Trough periods occur in April (250 encounters) and November (143 encounters).\n" +
                    "• Baseline Comparison: Current year throughput consistently outperforms prior year thresholds by an average margin of 24.8%, highlighting increased community trust and wider health coverage.\n" +
                    "• Operational Guidance: Calibrate nursing and physician station staffing ahead of anticipated quarterly surges to minimize patient wait times.",
                badgeText: "CAPACITY MONITORING"
            ));

            // Page Break for clean multi-page presentation
            col.Item().PageBreak();

            // ==========================================
            // 3. Average Wellness Score Breakdown
            // ==========================================
            col.Item().Element(c => ComposeSection(
                c,
                title: "3. Average Wellness Score Breakdown (7 Dimensions)",
                subtitle: "Holistic Health Evaluation Across Population Dimensions",
                imageBase64: Model.WellnessAspectsChartBase64,
                imageHeight: 160,
                clinicalSummary:
                    "Holistic Health Dimensions (0 - 100 Scale):\n" +
                    "• Strengths: Patients demonstrate robust resilience in Physical Well-being (88/100) and Spiritual Well-being (82/100), reflecting positive physical activity habits and strong community social capital.\n" +
                    "• Priority Deficits: Financial Health (60/100) and Mental Well-being (68/100) register as the lowest scoring dimensions across all demographic cohorts, followed closely by Emotional Health (71/100).\n" +
                    "• Strategic Intervention: Integrate medical social services and accessible mental health support counselors into primary wellness consultation workflows.",
                badgeText: "HOLISTIC SCREENING"
            ));

            // ==========================================
            // 4. Patient Smoker Status Distribution
            // ==========================================
            col.Item().Element(c => ComposeSection(
                c,
                title: "4. Patient Smoker Status & Nicotine Distribution",
                subtitle: "Combustible Tobacco vs. Electronic Nicotine Delivery Systems (ENDS)",
                imageBase64: Model.SmokerStatusChartBase64,
                imageHeight: 160,
                clinicalSummary:
                    "Tobacco & Vapor Exposure Profile:\n" +
                    "• Population Overview: 680 patients (69.0%) identify as non-smokers, while 305 patients (31.0%) report active nicotine consumption.\n" +
                    "• Modality Breakdown: Among active consumers, 210 patients (68.9%) consume traditional combustible cigarettes, while 95 patients (31.1%) use electronic cigarettes/vapes.\n" +
                    "• Targeted Clinical Action: The rising proportion of vape device users indicates emerging pulmonary and cardiovascular risk among younger cohorts. Station 2 (Triage) should initiate automatic brief cessation counseling for all self-reported users.",
                badgeText: "PREVENTIVE HEALTH"
            ));
        });
    }

    private void ComposeSection(
        IContainer container,
        string title,
        string subtitle,
        string? imageBase64,
        float imageHeight,
        string clinicalSummary,
        string badgeText)
    {
        container.Border(1).BorderColor("#e2e8f0").Background("#ffffff").Padding(12).Column(col =>
        {
            col.Item().Row(r =>
            {
                r.RelativeItem().Column(titleCol =>
                {
                    titleCol.Item().Text(title).FontSize(11.5f).Bold().FontColor("#0f172a");
                    titleCol.Item().Text(subtitle).FontSize(8.5f).FontColor("#64748b");
                });

                r.ConstantItem(120).AlignRight().Background("#f1f5f9").PaddingVertical(3).PaddingHorizontal(6).Text(badgeText)
                    .FontSize(7).SemiBold().FontColor("#475569");
            });

            col.Item().PaddingTop(8).Row(contentRow =>
            {
                contentRow.Spacing(12);

                // Chart visual on left side
                var imageBytes = DecodeBase64(imageBase64);
                if (imageBytes != null && imageBytes.Length > 0)
                {
                    contentRow.ConstantItem(220).Height(imageHeight).Border(1).BorderColor("#f1f5f9").Background("#f8fafc")
                        .Padding(4).Image(imageBytes).FitArea();
                }
                else
                {
                    contentRow.ConstantItem(220).Height(imageHeight).Border(1).BorderColor("#f1f5f9").Background("#f8fafc")
                        .AlignCenter().AlignMiddle().Text("Visualization Graph").FontSize(9).FontColor("#94a3b8");
                }

                // Clinical summary narrative on right side
                contentRow.RelativeItem().Column(descCol =>
                {
                    descCol.Item().Text("Clinical Review & Diagnostic Insights")
                        .FontSize(9.5f).SemiBold().FontColor("#0f766e");

                    descCol.Item().PaddingTop(4).Text(clinicalSummary)
                        .FontSize(8.5f).LineHeight(1.35f).FontColor("#334155");
                });
            });
        });
    }

    private void ComposeFooter(IContainer container)
    {
        container.Column(col =>
        {
            col.Item().LineHorizontal(1).LineColor("#e2e8f0");
            col.Item().PaddingTop(6).Row(row =>
            {
                row.RelativeItem().Text(
                    "CONFIDENTIAL CLINICAL RECORD — Electronic Health Record & Wellness System (eHPR). For authorized medical staff only.")
                    .FontSize(7.5f)
                    .FontColor("#94a3b8");

                row.ConstantItem(100).AlignRight().Text(text =>
                {
                    text.Span("Page ").FontSize(8).FontColor("#64748b");
                    text.CurrentPageNumber().FontSize(8).SemiBold().FontColor("#0f172a");
                    text.Span(" of ").FontSize(8).FontColor("#64748b");
                    text.TotalPages().FontSize(8).SemiBold().FontColor("#0f172a");
                });
            });
        });
    }

    private static byte[]? DecodeBase64(string? base64)
    {
        if (string.IsNullOrWhiteSpace(base64)) return null;
        try
        {
            var clean = base64;
            var commaIndex = clean.IndexOf(',');
            if (commaIndex >= 0)
            {
                clean = clean.Substring(commaIndex + 1);
            }
            return Convert.FromBase64String(clean);
        }
        catch
        {
            return null;
        }
    }
}
